### PR TITLE
New root cert

### PR DESCRIPTION
**Pull request by rubdos**
This has been generated in January already, and has now been swapped out.

We probably want to do a post-mortem on this, because no other Signal apps had any issue in the transition. I assume they started shipping both root certs at some point, and we should be aware of it when that happens.

### CODE REVIEW

**Comment by rubdos** [comment]
Dump:

```
Certificate:
    Data:
        Version: 3 (0x2)
        Serial Number:
            c1:f3:e2:0e:b4:70:80:c1:a4:fa:f5:83:26:7f:24:36:9a:3e:97
        Signature Algorithm: sha256WithRSAEncryption
        Issuer: C = US, ST = California, L = Mountain View, O = "Signal Messenger, LLC", CN = Signal Messenger
        Validity
            Not Before: Jan 26 00:45:51 2022 GMT
            Not After : Jan 24 00:45:50 2032 GMT
        Subject: C = US, ST = California, L = Mountain View, O = "Signal Messenger, LLC", CN = Signal Messenger
        Subject Public Key Info:
            Public Key Algorithm: rsaEncryption
                RSA Public-Key: (4096 bit)
                Modulus:
                    00:c4:79:c8:9f:c4:c1:c7:94:38:71:6c:44:55:74:
                    4a:ce:84:6b:0b:3b:4f:0f:51:d3:64:01:38:d9:d6:
                    44:f9:d6:e3:df:e4:93:e2:45:bb:ac:f4:5e:09:fc:
                    68:01:43:80:0d:48:08:c8:0d:9b:85:63:45:8e:bc:
                    6f:e2:d2:ab:f1:b6:1a:56:ef:4a:1c:a7:c2:23:92:
                    25:93:36:20:3c:d7:34:0d:41:d0:a2:59:b1:83:53:
                    80:75:b0:b8:b6:a3:82:60:24:cc:1e:4a:44:05:8b:
                    20:f2:9e:a5:a0:1e:9c:3e:2a:6b:f2:b4:2c:d1:5a:
                    7b:eb:ae:9b:48:7c:4e:06:3f:13:4e:b0:0b:57:15:
                    b5:47:fb:ef:09:3b:8d:88:68:a4:55:95:b7:e9:7b:
                    f9:54:1d:b8:e2:62:62:29:42:ba:19:3c:63:d8:e0:
                    ea:a5:f0:a3:37:a3:7f:4e:6c:f9:d3:a3:55:a8:33:
                    89:a8:c8:e3:99:a5:4d:e5:57:56:b0:7e:db:d6:07:
                    1d:6c:6d:30:4b:d3:6b:10:59:f1:d1:c6:03:55:17:
                    e3:e3:d1:f7:43:30:c1:5d:14:9a:1b:02:ba:cb:55:
                    f2:b6:51:af:9d:60:de:29:57:95:c8:c7:35:5a:ad:
                    24:56:ef:70:97:a9:0f:b6:aa:5a:0f:5b:fc:a7:a5:
                    ad:e0:46:d6:1e:19:65:78:8e:5e:de:0f:43:e6:78:
                    7a:4a:39:8e:fc:89:d3:f8:1f:58:df:02:fd:13:01:
                    57:8a:a6:e0:79:64:56:76:b3:37:32:4b:1a:d0:6b:
                    c7:7b:14:87:f4:90:d2:5e:f6:02:11:8d:b4:3e:5e:
                    bb:e7:37:e6:59:be:3e:9d:fb:cb:81:26:af:0b:7d:
                    06:85:86:55:5f:23:4f:da:21:d8:20:49:c6:a9:47:
                    bc:3c:a0:ba:6f:75:f9:54:5a:a7:13:2d:e5:d5:34:
                    b5:6b:83:5e:5c:10:3c:1d:95:5f:0f:56:c7:13:fc:
                    a4:f4:6d:f3:73:28:8f:34:a8:1a:bc:2f:24:66:6a:
                    e0:2a:3f:40:83:8d:ac:98:19:bd:94:01:a6:e7:85:
                    e7:e0:99:16:3a:68:11:39:99:7c:5d:6f:20:04:cf:
                    30:92:de:f0:f1:8d:e4:c3:f2:ff:27:6c:3a:be:48:
                    3e:a5:26:2d:22:ee:38:30:11:f3:43:85:ef:57:2b:
                    9d:1b:68:ad:79:51:d7:3c:0a:bf:d9:96:11:8c:8c:
                    d9:96:a8:17:74:8c:8a:5a:66:6d:6b:cd:60:34:93:
                    85:70:5e:d0:f0:a4:15:d2:cf:ca:01:16:c8:62:5e:
                    cd:c5:0f:a8:c7:63:62:21:39:1d:e9:a5:bc:9d:e2:
                    a4:54:a7
                Exponent: 65537 (0x10001)
        X509v3 extensions:
            X509v3 Key Usage: critical
                Certificate Sign, CRL Sign
            X509v3 Basic Constraints: critical
                CA:TRUE
            X509v3 Subject Key Identifier:
                B5:F3:4B:C6:E5:D6:4B:D0:E5:80:6B:8C:50:C3:67:5B:BC:B1:F3:71
            X509v3 Authority Key Identifier:
                keyid:B5:F3:4B:C6:E5:D6:4B:D0:E5:80:6B:8C:50:C3:67:5B:BC:B1:F3:71

    Signature Algorithm: sha256WithRSAEncryption
         15:1e:8a:bc:92:d2:a8:f2:90:13:7b:e5:aa:07:3b:d6:d5:3e:
         ba:d7:f8:34:89:20:1f:55:d9:8c:e4:15:5c:a1:fe:2a:3a:e5:
         02:4c:1b:c9:da:59:51:8e:4a:95:51:c1:4c:21:65:52:a1:dc:
         95:69:fe:68:8f:83:34:c6:02:8e:f3:86:b0:c8:a1:77:3e:8a:
         1e:e8:ac:03:1b:d7:da:a8:97:fd:87:6b:c3:99:2d:ae:f9:2e:
         88:c9:35:16:d9:a0:24:79:0b:e8:0c:f0:2f:ac:a4:c2:e3:15:
         ff:64:dc:95:71:75:a8:e1:b5:15:1c:47:4c:d8:87:0b:01:4b:
         ba:99:e4:c7:b4:77:a8:11:5c:3d:19:89:26:da:74:c3:31:4b:
         0e:8a:7c:a9:37:78:f9:8f:6f:d8:17:f8:c4:53:4b:ad:dc:f2:
         62:f3:55:80:7f:dd:f7:bf:6e:4a:6a:e1:15:30:cd:41:ef:a1:
         97:fe:49:40:fb:37:34:90:45:04:0c:7e:f0:07:97:19:35:d5:
         35:4d:c5:27:18:3e:dc:57:0f:28:b2:dc:2b:2c:97:d8:16:ae:
         b5:aa:43:fa:26:b8:78:a9:a0:7e:b6:27:b8:7c:28:06:1b:af:
         aa:04:22:af:82:ce:e7:a7:73:77:82:20:11:81:05:fb:c2:a6:
         e1:4e:81:c9:00:5d:71:38:32:50:5a:b0:45:34:30:ee:ba:1a:
         b4:c2:80:cb:7d:6c:09:92:c3:74:eb:44:fd:76:f9:95:05:c5:
         83:6d:a9:69:6e:45:4f:09:59:0e:05:08:23:dc:cf:da:60:31:
         10:4e:82:7e:25:4f:10:d9:1b:e2:38:ec:e2:8d:b9:24:63:14:
         43:fd:e1:c7:60:c5:dd:c7:ff:90:4a:ed:61:d4:cf:5b:40:19:
         0e:01:81:ea:52:5e:09:a3:ce:27:c5:4f:91:55:4c:34:e5:dd:
         99:d6:51:50:57:88:76:2d:6c:e0:60:2e:24:88:91:ba:86:30:
         22:ed:ac:1b:45:21:e4:3b:45:14:db:dc:bf:88:13:d4:74:50:
         1d:1c:24:1d:c0:5d:b7:f5:95:59:0e:72:6a:dd:bb:68:7c:03:
         7d:9a:0b:0b:6b:e5:2d:5f:04:5d:6e:9e:51:bb:8a:63:e6:a8:
         97:e9:38:c5:9a:f3:22:05:fc:a5:95:9b:6f:49:00:fa:bc:2e:
         bb:32:6d:bd:33:e6:08:3c:c3:b6:5b:94:4b:81:f7:33:96:f4:
         cd:e5:eb:40:d7:b8:93:ba:97:b8:3e:75:e5:7a:3f:de:ab:bf:
         6b:a7:1d:2f:14:96:f5:a2:55:60:f2:f6:a7:e0:00:98:b3:cb:
         2d:e4:a8:ce:25:3b:00:47
```

**Comment by rubdos** [comment]
@nanu-c, maybe you're hitting this too.

**Comment by rubdos** [comment]
Tested on Whisperfish and seems to work.

**Comment by gferon** [comment]
Thanks a lot for promptly fixing this! What about adding a job in CI that compares what they have in their repo?

**Comment by rubdos** [comment]
> Thanks a lot for promptly fixing this! What about adding a job in CI that compares what they have in their repo?

It would already fail, because we don't ship the old one any more :'-)

**Pull request merged**
