### PR TITLE
Contact discovery

### PR DESCRIPTION
**Pull request by rubdos**
Small patch, but depends on #50 because I didn't want to get into `String`-hell again :'-)

Will rebase once I get #50 finished.

### CODE REVIEW

**Comment by Be-ing** [comment]
#50 has been merged and this has some merge conflicts now. Could you rebase?

**Comment by rubdos** [comment]
> #50 has been merged and this has some merge conflicts now. Could you rebase?

It's quite a bit of conflicts, sadly. I'll rebase when I work again on contact discovery; except if you want to continue this really soon?

**Comment by Be-ing** [comment]
> if you want to continue this really soon?

Rebasing someone else's branch isn't a very nice way to get started in a new codebase.

**Comment by rubdos** [comment]
So, I've rebased this now, but `retrieveDirectory` / `/v1/directory/tokens` seems like it's gone from the Signal client. We probably want to drop this and implement the new contact discovery protocol with attestation.

**Comment by rubdos** [comment]
> the new contact discovery protocol with attestation.

Result of some investigative work:

Android's `ContactDiscoveryRefreshV1.java` contains the currently working logic to do contact lookup. However, Signal has been working on a V2, `ContactDiscoveryRefreshV2.kt` (notice Kotlin), tied to https://github.com/signalapp/ContactDiscoveryService. This version 2 has no endpoint on the production servers yet, but it has a lot of recent activity, and might replace V1 sooner than we want. Version 2 also has [some components in Signal-Client](https://github.com/signalapp/libsignal/tree/main/rust/attest), such that we don't have to implement everything ourselves.

So either we implement both, or we wait a bit longer until v2 is moved into production.

**Comment by rubdos** [comment]
In other news: these Rust components in libsignal-client require `ecdsa` `^0.13`, which transitively depends on Rust 2021 and is as such currenly unusable in Whisperfish (because we're still on 1.52-dev, which on itself is not *that* old... come on library devs, please don't do this...)

Downgrading those versions leads to other impossibilities (`ecdsa`'s feature `serde` only exists in 0.13).

**Comment by rubdos** [comment]
This stuff is completely deprecated and disfunctional by now. We should implement the new PNI system instead.

**Pull request closed without merging**
