### PR TITLE
Update libsignal to v0.32.0

### LINKED ISSUE #244: Upgrade to libsignal v0.31 or later
Needed due to my attempt to use presage without the zeroize dependency which conflicts with sqlx https://github.com/signalapp/curve25519-dalek/pull/9#issuecomment-1716045982

### PR DESCRIPTION
**Pull request by gferon**
Fixes #244 (and long running issues with upgrading dependencies since `zeroize` was pinned by `curve25519-dalek` was bumped to 4.0.0)

Just a draft for now because I haven't tested it yet 😂

### CODE REVIEW

**Comment by boxdot** [comment]
Tested with https://github.com/whisperfish/presage/pull/188 in gurk CLI client. Works for me.

**Review by rubdos — APPROVED** [review]
Omg they got rid of the `Context`.

I might come back and change to `proc-macro2 = "1.0"`-style dependencies. That shouldn't conflict with us nor with you.

**Comment by gferon** [comment]
I'd need to double check that groups sync still works as intended.

**Comment by gferon** [comment]
> Omg they got rid of the Context.

In theory, this means `Send` is possible now.

**Pull request merged**
