### PR TITLE
Dependency updates

### PR DESCRIPTION
**Pull request by rubdos**
Now that we have 1.75... we can bump all the things!

I'm keeping away from  bumping -protocol now.

### CODE REVIEW

**Comment by rubdos** [comment]
Cherry picked and fixed the protobuf dep from #270

**Comment by rubdos** [comment]
> Comparison is base [(`ce4ba97`)](https://app.codecov.io/gh/whisperfish/libsignal-service-rs/commit/ce4ba9707d83b7626357828ee08be12ea34173f6?el=desc&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=whisperfish) 3.60% compared to head [(`f7a28d0`)](https://app.codecov.io/gh/whisperfish/libsignal-service-rs/pull/280?src=pr&el=desc&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=whisperfish) 17.25%.

Hmm. We didn't have libsignal-service in CI for testing and coverage, I added it here.

**Comment by rubdos** [comment]
Bumps MSRV to 1.75 because of [RPITIT](https://rust-lang.github.io/rfcs/3425-return-position-impl-trait-in-traits.html). I anticipate this quickly will get traction in several libs.

**Comment by rubdos** [comment]
I saw some funky behaviour, the websocket seemed to be resetting.

```
2024-01-10T17:45:32.869635Z ERROR whisperfish::worker::client: Error starting stream: Websocket error: HTTP status 504 Gateway Timeout
2024-01-10T17:45:32.869732Z  INFO whisperfish::worker::client: Retrying in 10
```

```
2024-01-10T17:46:06.972704Z TRACE websocket: libsignal_service_hyper::websocket: Will start websocket at Url { scheme: "wss", cannot_be_a_base: false, username: "", password: None, host: Some(Domain("chat.signal.org")), port: None, path: "/v1/websocket/", query: None, fragment: None }
2024-01-10T17:46:07.102194Z  WARN libsignal_service_hyper::websocket: Websocket closing: Some(CloseFrame { code: Error, reason: "org.eclipse.jetty.websocket.core.exception.WebSocketException: WebSocketResourceProvider OPEN method error: WebSocketConnec" })
2024-01-10T17:46:07.922719Z ERROR set up message receiver:websocket: libsignal_service::websocket: SignalWebSocket: Websocket error: end of web request stream; socket closing
2024-01-10T17:46:07.923564Z  INFO libsignal_service::messagepipe: sink was closed: Ok(())
2024-01-10T17:46:07.923604Z DEBUG whisperfish::worker::client: Attempting reconnect
```

**Review by gferon — APPROVED** [review]
Ship it! 🚢 🚀

**Pull request merged**
