### PR TITLE
Implement profile avatar retention

### PR DESCRIPTION
**Pull request by rubdos**
Will test now.

### CODE REVIEW

**Comment by rubdos** [comment]
This only [works after Rust 1.53](https://github.com/rust-lang/rust/pull/79278), so I'm desugaring the or-patterns for now.

**Comment by rubdos** [comment]
This seems to work well.

**Review by gferon — APPROVED** [review]
LGTM! I'm only starting to think that we should think twice before adding more primitive arguments to our function and maybe introduce types so we can add variants later, but here it's perfectly fine 👍🏼🥳

**Comment by rubdos** [comment]
> LGTM! I'm only starting to think that we should think twice before adding more primitive arguments to our function and maybe introduce types so we can add variants later, but here it's perfectly fine 👍🏼partying_face

I agree. In this case, it makes the methods very Rusty, I feel.

**Pull request merged**
