### PR TITLE
MessageSender to use the WS instead of a service

### PR DESCRIPTION
**Pull request by rubdos**
This seems to have been deprecated for a long time now, and it minimizes the amount of needed connections.

### CODE REVIEW

**Comment by rubdos** [comment]
Sending works, fetching pre-keys does not yet.

**Comment by rubdos** [comment]
Apparently pre-keys should remain via the push service.

**Comment by rubdos** [comment]
This works and seems trivial enough to merge as-is. Let me know if the breakage is too much :-)

**Comment by gferon** [comment]
> This works and seems trivial enough to merge as-is. Let me know if the breakage is too much :-)

If it works then 💯

**Comment by rubdos** [comment]
> > This works and seems trivial enough to merge as-is. Let me know if the breakage is too much :-)
> 
> If it works then 100

It does, and it seems equivalent (apart from some error handling/fall back code) with the Android code too :-)

**Pull request merged**
